/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue Sep 15 09:34:03 1998
 */
#ifndef __CEXTRACT__
#ifdef __STDC__

extern void EditDirtyAc ( Widget w, XEvent * event, String * argv, Cardinal * argc );
extern void Nop ( Widget w, XEvent * event, String * argv, Cardinal * argc );
extern void main ( int argc, char **argv, char **env );
extern int GetType ( object *tmp );
extern Attr AttrCreate ( char *name, App app, object *ob, AttrDef *desc, unsigned long flags, Edit edit );
extern void AttrChange ( Attr self, object *ob, unsigned long flags, Edit edit );
extern void AttrDestroy ( Attr self );
extern void AttrApply ( Attr self );
extern void CrEditRefresh ( Widget w, XRectangle rect );
extern void CrEditBorderOff ( Widget w );
extern void CrEditSelect ( Widget w, XRectangle rect );
extern CrListNode GetYNode ( Widget w, int y );
extern CrListCall GetYCall ( Widget w, int y );
extern void FaceDraw ( Widget w, GC gc, New_Face *face, int x, int y );
extern GC GCCreate ( Widget w );
extern void EditResizeScroll ( Edit self, int width, int height, int dx, int dy );
extern Edit EditCreate ( App app, EditType type, String path );
extern void EditDestroy ( Edit self );
extern void EditUpdate ( Edit self );
extern EditReturn EditSave ( Edit self );
extern void EditPerformFill ( Edit self, int x, int y );
extern void EditPerformFillBelow ( Edit self, int x, int y );
extern void EditFillRectangle ( Edit self, XRectangle rec );
extern void EditWipeRectangle ( Edit self, XRectangle rec );
extern void EditShaveRectangle ( Edit self, XRectangle rec );
extern void EditShaveRectangleBelow ( Edit self, XRectangle rec );
extern void EditCopyRectangle ( Edit self, Edit src, XRectangle rect, int sx, int sy );
extern void EditDeletePoint ( Edit self, int x, int y );
extern void EditModified ( Edit self );
extern void EditUnmodified ( Edit self );
extern Boolean EditDelete ( Edit self, int x, int y, int z );
extern Boolean EditObjectDelete ( Edit self, int x, int y, int z );
extern object *EditCloneInsert ( Edit self, object *obj, int x, int y, int z );
extern Boolean EditInsert ( Edit self, int x, int y, int z );
extern Boolean EditObjectInsert ( Edit self, object *obj, int x, int y, int z );
extern void EditSetPath ( Edit self, String path );
extern App AppCreate ( XtAppContext appCon, String displayString, XtResource resources[], Cardinal resourcesNum, XrmOptionDescRec *options, Cardinal optionsNum, int *argc, char *argv[] );
extern void AppDestroy ( App self );
extern void AppUpdate ( App self );
extern void AppSelectSet ( App self, Edit edit, XRectangle rect );
extern void AppSelectUnset ( App self );
extern void AppItemSet ( App self, Edit edit, object *obj, int wallSet );
extern char PixelFromAlias ( char *name );
extern void InitializeColors ( Display *dpy );
extern Edit AppEditInsert ( App self, String path, EditType type );
extern void AppEditAttach ( App self, Edit edit );
extern void AppEditDeattach ( App self, Edit edit );
extern void BitmapsCreate ( Display *d );
extern char *StrPathNormalize ( char *this, char *src );
extern char *StrPathCd ( char *cwd, const char *cd );
extern char *StrPathGenCd ( char *cwd, const char *dstArg );
extern char *StrBasename ( char *basename, const char *filename );
extern XChar2b fontindex_to_XChar2b ( Fontindex s );
extern int ReadPixmaps ( Display *gdisp, Pixmap **pixmaps, Pixmap **masks, Colormap *cmap );
extern void free_pixmaps ( Display *gdisp, Pixmap *pixmaps );
extern Pixmap *ReadBitmaps ( Display *d );
extern void set_font_path ( Display *dpy, char *path );
extern int check_font_path ( Display *dpy );
extern int fixfontpath ( Display *disp, char *name );
extern int allocate_colors ( Display *disp, Window w, long screen_num, Colormap *colormap, XColor discolor[13 ] );
extern int ReadImages(Display *gdisp, Pixmap **pixmaps, Pixmap **masks,  Colormap *cmap, enum DisplayMode type);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
