/* cfnewspaper.c */
void do_sql(const char *sql, sqlite3 *base);
int get_living_id(object *living);
int get_region_id(region *reg);
int get_map_id(mapstruct *map);
void format_time(timeofday_t *tod, char *buffer, int size);
int get_time_id(timeofday_t *tod, int create);
void read_parameters(void);
int initPlugin(const char *iversion, f_plug_api gethooksptr);
void *getPluginProperty(int *type, ...);
int runPluginCommand(object *op, char *params);
void *globalEventListener(int *type, ...);
int postInitPlugin(void);
paper_properties *get_newspaper(const char *name);
void news_cat(char *buffer, int size, const char *format, ...);
void do_kills(char *buffer, int size, time_t start, time_t end, const char *reg, kill_format *format);
void do_region_kills(region *reg, char *buffer, int size, time_t start, time_t end);
void do_region(region *reg, char *buffer, int size, time_t start, time_t end);
void do_world_kills(char *buffer, int size, time_t start, time_t end);
void do_world(char *buffer, int size, time_t start, time_t end);
void get_newspaper_content(object *paper, paper_properties *properties, region *reg);
void *eventListener(int *type, ...);
int closePlugin(void);
