#!/bin/sh
#
# This is a replacement for the crosserv.pl perl script.,
# No point in using perl for such a simple task.

CMDNAME="BINDIR/crossfire"
maxrestart=500
logdir="/usr/games/crossfire/var/logs"


logcount=0

rm -rf $logdir
mkdir $logdir

while [ ! "$logcount"x = "$maxrestart"x ]; do
  echo "Starting Crossfire `date` for the $logcount time..." >>$logdir/crossfire.log 2>&1
  $CMDNAME -d 2>>$logdir/crossfire.log 1>&2
  if [ -f core ] ; then
        mv core core.$logcount
        /bin/gzip core.$logcount
  fi
  logcount=`expr $logcount + 1`
  sleep 50
done
