typedef void (*gfec_error_handler)(const char *error_message);
void gfec_eval_file(const char *file, gfec_error_handler error_handler);
void gfec_eval_string(const char *str, gfec_error_handler error_handler);
static SCM gfec_catcher(void *data, SCM tag, SCM throw_args);

/*extern SCM Script_increaseObjectCount(SCM what, SCM increment);*/
/*extern SCM Script_decreaseObjectCount(SCM what, SCM decrement);*/
extern SCM Script_setCursed(SCM who, SCM value);
extern SCM Script_activateRune(SCM who, SCM what);
extern SCM Script_checkTrigger(SCM who, SCM what);
extern SCM Script_setUnaggressive(SCM who, SCM value);

extern SCM Script_castAbility(SCM who, SCM spell, SCM direction, SCM options);
extern SCM Script_getMapPath(SCM where);
extern SCM Script_getMapObject(SCM where);
extern SCM Script_getMessage(SCM who);
extern SCM Script_getGod(SCM who);
extern SCM Script_setGod(SCM who, SCM value);
extern SCM Script_setWeight(SCM who, SCM value);
extern SCM Script_readyMap(SCM mapname);
extern SCM Script_outOfMap_p(SCM who, SCM x, SCM y);
extern SCM Script_pickUp(SCM who, SCM what);
extern SCM Script_getWeight(SCM who);
extern SCM Script_NoPick_p(SCM who);
extern SCM Script_getMap(SCM who);
extern SCM Script_getNextObject(SCM who);
extern SCM Script_getPreviousObject(SCM who);
extern SCM Script_getFirstOnSquare(SCM where, SCM x, SCM y);
extern SCM Script_setQuantity(SCM what, SCM value);
extern SCM Script_getQuantity(SCM what);
extern SCM Script_insertObjectInside(SCM what, SCM where);
extern SCM Script_findPlayer(SCM plname);
extern SCM Script_apply(SCM who, SCM what, SCM flags);
extern SCM Script_drop(SCM who, SCM value);
extern SCM Script_take(SCM who, SCM value);
extern SCM Script_getGP(SCM who);
extern SCM Script_setGP(SCM who, SCM value);
extern SCM Script_getScriptQuantum();
extern SCM Script_getRemainingQuantum();
extern SCM Script_setInvisible(SCM who, SCM value);
extern SCM Script_invisible_p(SCM who);
extern SCM Script_getXP(SCM who);
extern SCM Script_setXP(SCM who, SCM value);
extern SCM Script_getSpeed(SCM who);
extern SCM Script_setSpeed(SCM who, SCM value);
extern SCM Script_getFP(SCM who);
extern SCM Script_getGP(SCM who);
extern SCM Script_setFP(SCM who, SCM value);
extern SCM Script_setGP(SCM who, SCM value);
extern SCM Script_getReturnValue();
extern SCM Script_setReturnValue(SCM value);
extern SCM Script_getDirection(SCM who);
extern SCM Script_setDirection(SCM who, SCM value);

extern SCM Script_getScriptDeath(SCM who);
extern SCM Script_getScriptLoad(SCM who);
extern SCM Script_getScriptApply(SCM who);
extern SCM Script_getScriptSay(SCM who);
extern SCM Script_getScriptTrigger(SCM who);
extern SCM Script_getScriptTime(SCM who);
extern SCM Script_getScriptAttack(SCM who);
extern SCM Script_getScriptDrop(SCM who);
extern SCM Script_getScriptThrow(SCM who);
extern SCM Script_getScriptStop(SCM who);
extern SCM Script_setScriptDeath(SCM who, SCM value);
extern SCM Script_setScriptLoad(SCM who, SCM value);
extern SCM Script_setScriptApply(SCM who, SCM value);
extern SCM Script_setScriptSay(SCM who, SCM value);
extern SCM Script_setScriptTrigger(SCM who, SCM value);
extern SCM Script_setScriptTime(SCM who, SCM value);
extern SCM Script_setScriptAttack(SCM who, SCM value);
extern SCM Script_setScriptDrop(SCM who, SCM value);
extern SCM Script_setScriptThrow(SCM who, SCM value);
extern SCM Script_setScriptStop(SCM who, SCM value);
extern SCM Script_getLastSP(SCM who);
extern SCM Script_setLastSP(SCM who, SCM value);
extern SCM Script_getLastGP(SCM who);
extern SCM Script_setLastGP(SCM who, SCM value);
extern SCM Script_fixObject(SCM who);
extern SCM Script_teleport(SCM who, SCM where, SCM x, SCM y);
extern SCM Script_setFace(SCM who, SCM value);
extern SCM Script_setAttackType(SCM who, SCM value);
extern SCM Script_getAttackType(SCM who);
extern SCM Script_getDamage(SCM who);
extern SCM Script_setDamage(SCM who, SCM value);
extern SCM Script_setBeenApplied(SCM who, SCM value);
extern SCM Script_setIdentified(SCM who, SCM value);
extern SCM Script_killObject(SCM killer, SCM killed, SCM type);
extern SCM Script_whoIsOther();
extern SCM Script_directionNorth();
extern SCM Script_directionNE();
extern SCM Script_directionEast();
extern SCM Script_directionSE();
extern SCM Script_directionSouth();
extern SCM Script_directionSW();
extern SCM Script_directionWest();
extern SCM Script_directionNW();
extern SCM Script_castSpell(SCM who, SCM spell, SCM direction, SCM options);
extern SCM Script_forgetSpell(SCM who, SCM spell);
extern SCM Script_acquireSpell(SCM who, SCM spell);
extern SCM Script_knowSpell_p(SCM who, SCM spell);
extern SCM Script_checkInvisibleObjectInside(SCM idname, SCM who);
extern SCM Script_createInvisibleObjectInside(SCM idname, SCM where);
extern SCM Script_createObjectInside(SCM archname, SCM where);
extern SCM Script_checkArchetype(SCM what, SCM mapinfo, SCM x, SCM y);
extern SCM Script_checkInventory(SCM who, SCM what);
extern SCM Script_getName(SCM who);
extern SCM Script_createObject(SCM archname, SCM x, SCM y);
extern SCM Script_removeObject(SCM what);
extern SCM Script_isAlive_p(SCM who);
extern SCM Script_isWiz_p(SCM who);
extern SCM Script_wasWiz_p(SCM who);
extern SCM Script_isApplied_p(SCM who);
extern SCM Script_isUnpaid_p(SCM who);
extern SCM Script_isFlying_p(SCM who);
extern SCM Script_isMonster_p(SCM who);
extern SCM Script_isFriendly_p(SCM who);
extern SCM Script_isGenerator_p(SCM who);
extern SCM Script_isThrown_p(SCM who);
extern SCM Script_canSeeInvisible_p(SCM who);
extern SCM Script_canRoll_p(SCM who);
extern SCM Script_isTurnable_p(SCM who);
extern SCM Script_isUsedUp_p(SCM who);
extern SCM Script_isIdentified_p(SCM who);
extern SCM Script_isSplitting_p(SCM who);
extern SCM Script_hitback_p(SCM who);
extern SCM Script_blocksview_p(SCM who);
extern SCM Script_isUndead_p(SCM who);
extern SCM Script_isScared_p(SCM who);
extern SCM Script_isUnaggressive_p(SCM who);
extern SCM Script_reflectMissiles_p(SCM who);
extern SCM Script_reflectSpells_p(SCM who);
extern SCM Script_runAway_p(SCM who);
extern SCM Script_canPassThru_p(SCM who);
extern SCM Script_canPickUp_p(SCM who);
extern SCM Script_isUnique_p(SCM who);
extern SCM Script_canCastSpell_p(SCM who);
extern SCM Script_canUseScroll_p(SCM who);
extern SCM Script_canUseWand_p(SCM who);
extern SCM Script_canUseBow_p(SCM who);
extern SCM Script_canUseArmour_p(SCM who);
extern SCM Script_canUseWeapon_p(SCM who);
extern SCM Script_canUseRing_p(SCM who);
extern SCM Script_hasXRays_p(SCM who);
extern SCM Script_isFloor_p(SCM who);
extern SCM Script_isLifesave_p(SCM who);
extern SCM Script_isSleeping_p(SCM who);
extern SCM Script_standStill_p(SCM who);
extern SCM Script_onlyAttack_p(SCM who);
extern SCM Script_isConfused_p(SCM who);
extern SCM Script_hasStealth_p(SCM who);
extern SCM Script_isCursed_p(SCM who);
extern SCM Script_isDamned_p(SCM who);
extern SCM Script_knownMagical_p(SCM who);
extern SCM Script_knownCursed_p(SCM who);
extern SCM Script_canUseSkill_p(SCM who);
extern SCM Script_beenApplied_p(SCM who);
extern SCM Script_canUseRod_p(SCM who);
extern SCM Script_canUseHorn_p(SCM who);
extern SCM Script_makeInvisible_p(SCM who);
extern SCM Script_isBlind_p(SCM who);
extern SCM Script_canSeeInDark_p(SCM who);
extern SCM Script_getAC(SCM who);
extern SCM Script_getCha(SCM who);
extern SCM Script_getCon(SCM who);
extern SCM Script_getDex(SCM who);
extern SCM Script_getHP(SCM who);
extern SCM Script_getInt(SCM who);
extern SCM Script_getMaxHP(SCM who);
extern SCM Script_getMaxSP(SCM who);
extern SCM Script_getPow(SCM who);
extern SCM Script_getSP(SCM who);
extern SCM Script_getStr(SCM who);
extern SCM Script_getWis(SCM who);
extern SCM Script_getXPosition(SCM who);
extern SCM Script_getYPosition(SCM who);
extern SCM Script_setAC(SCM who, SCM newvalue);
extern SCM Script_setCha(SCM who, SCM newvalue);
extern SCM Script_setCon(SCM who, SCM newvalue);
extern SCM Script_setDex(SCM who, SCM newvalue);
extern SCM Script_setHP(SCM who, SCM newvalue);
extern SCM Script_setInt(SCM who, SCM newvalue);
extern SCM Script_setMaxHP(SCM who, SCM newvalue);
extern SCM Script_setMaxSP(SCM who, SCM newvalue);
extern SCM Script_setPow(SCM who, SCM newvalue);
extern SCM Script_setSP(SCM who, SCM newvalue);
extern SCM Script_setStr(SCM who, SCM newvalue);
extern SCM Script_setWis(SCM who, SCM newvalue);
extern SCM Script_setTitle(SCM who, SCM newname);
extern SCM Script_setPosition(SCM who, SCM x, SCM y);
extern SCM Script_crossfireSay(SCM who, SCM message);
extern SCM Script_crossfireMessage(SCM message, SCM color);
extern SCM Script_crossfireWrite(SCM who, SCM message, SCM color);
extern SCM Script_whoAmI();
extern SCM Script_whoIsActivator();
extern SCM Script_whatMessage();
extern SCM Script_getType(SCM who);
extern SCM Script_isType(SCM who, SCM what);

/* Crossfire Color Types */
extern SCM Script_colorBlack();
extern SCM Script_colorDarkBlue();
extern SCM Script_colorRed();
extern SCM Script_colorDarkYellow();
extern SCM Script_colorLightBlue();
extern SCM Script_colorOrange();
extern SCM Script_colorDarkGreen();
extern SCM Script_colorLightGreen();
extern SCM Script_colorGrey();
extern SCM Script_colorBrown();
extern SCM Script_colorYellow();
extern SCM Script_colorLightYellow();

/* Crossfire Attack Types */
extern SCM Script_attackTypePhysical();
extern SCM Script_attackTypeMagic();
extern SCM Script_attackTypeFire();
extern SCM Script_attackTypeElectricity();
extern SCM Script_attackTypeCold();
extern SCM Script_attackTypeConfusion();
extern SCM Script_attackTypeAcid();
extern SCM Script_attackTypeDrain();
extern SCM Script_attackTypeWeaponmagic();
extern SCM Script_attackTypeGhosthit();
extern SCM Script_attackTypePoison();
extern SCM Script_attackTypeSlow();
extern SCM Script_attackTypeParalyze();
extern SCM Script_attackTypeTurnUndead();
extern SCM Script_attackTypeFear();
extern SCM Script_attackTypeCancellation();
extern SCM Script_attackTypeDepletion();
extern SCM Script_attackTypeDeath();
extern SCM Script_attackTypeChaos();
extern SCM Script_attackTypeCounterspell();
extern SCM Script_attackTypeGodpower();
extern SCM Script_attackTypeHolyWord();
extern SCM Script_attackTypeBlind();

/* Crossfire Object Types */
extern SCM Script_typePlayer();
extern SCM Script_typeBullet();
extern SCM Script_typeRod();
extern SCM Script_typeTreasure();
extern SCM Script_typePotion();
extern SCM Script_typeFood();
extern SCM Script_typePoison();
extern SCM Script_typeBook();
extern SCM Script_typeClock();
extern SCM Script_typeFBullet();
extern SCM Script_typeFBall();
extern SCM Script_typeLightning();
extern SCM Script_typeArrow();
extern SCM Script_typeBow();
extern SCM Script_typeWeapon();
extern SCM Script_typeArmour();
extern SCM Script_typePedestal();
extern SCM Script_typeAltar();
extern SCM Script_typeConfusion();
extern SCM Script_typeLockedDoor();
extern SCM Script_typeSpecialKey();
extern SCM Script_typeMap();
extern SCM Script_typeDoor();
extern SCM Script_typeKey();
extern SCM Script_typeMMissile();
extern SCM Script_typeTimedGate();
extern SCM Script_typeTrigger();
extern SCM Script_typeGrimReaper();
extern SCM Script_typeMagicEar();
extern SCM Script_typeTriggerButton();
extern SCM Script_typeTriggerAltar();
extern SCM Script_typeTriggerPedestal();
extern SCM Script_typeShield();
extern SCM Script_typeHelmet();
extern SCM Script_typeHorn();
extern SCM Script_typeMoney();
extern SCM Script_typeClass();
extern SCM Script_typeGravestone();
extern SCM Script_typeAmulet();
extern SCM Script_typePlayerMover();
extern SCM Script_typeTeleporter();
extern SCM Script_typeCreator();
extern SCM Script_typeSkill();
extern SCM Script_typeExperience();
extern SCM Script_typeEarthwall();
extern SCM Script_typeGolem();
extern SCM Script_typeBomb();
extern SCM Script_typeThrownObject();
extern SCM Script_typeBlindness();
extern SCM Script_typeGod();
extern SCM Script_typeDetector();
extern SCM Script_typeSpeedBall();
extern SCM Script_typeDeadObject();
extern SCM Script_typeDrink();
extern SCM Script_typeMarker();
extern SCM Script_typeHolyAltar();
extern SCM Script_typePlayerChanger();
extern SCM Script_typeBattleground();
extern SCM Script_typePeacemaker();
extern SCM Script_typeGem();
extern SCM Script_typeFirechest();
extern SCM Script_typeFirewall();
extern SCM Script_typeCheckInv();
extern SCM Script_typeMoodFloor();
extern SCM Script_typeExit();
extern SCM Script_typeEncounter();
extern SCM Script_typeShopFloor();
extern SCM Script_typeShopMat();
extern SCM Script_typeRing();
extern SCM Script_typeFlesh();
extern SCM Script_typeInorganic();
extern SCM Script_typeLighter();
extern SCM Script_typeTrapPart();
extern SCM Script_typeSpellbook();
extern SCM Script_typeCloak();
extern SCM Script_typeCone();
extern SCM Script_typeAura();
extern SCM Script_typeSpinner();
extern SCM Script_typeGate();
extern SCM Script_typeButton();
extern SCM Script_typeHandle();
extern SCM Script_typeHole();
extern SCM Script_typeTrapdoor();
extern SCM Script_typeWordOfRecall();
extern SCM Script_typeParaimage();
extern SCM Script_typeSign();
extern SCM Script_typeBoots();
extern SCM Script_typeGloves();
extern SCM Script_typeConverter();
extern SCM Script_typeBracers();
extern SCM Script_typePoisoning();
extern SCM Script_typeSavebed();
extern SCM Script_typePoisonCloud();
extern SCM Script_typeFireholes();
extern SCM Script_typeWand();
extern SCM Script_typeAbility();
extern SCM Script_typeScroll();
extern SCM Script_typeDirector();
extern SCM Script_typeGirdle();
extern SCM Script_typeForce();
extern SCM Script_typePotionEffect();
extern SCM Script_typeCloseContainer();
extern SCM Script_typeContainer();
extern SCM Script_typeArmourImprover();
extern SCM Script_typeWeaponImprover();
extern SCM Script_typeSkillScroll();
extern SCM Script_typeDeepSwamp();
extern SCM Script_typeIdentifyAltar();
extern SCM Script_typeCancellation();
extern SCM Script_typeMenu();
extern SCM Script_typeBallLightning();
extern SCM Script_typeSwarmSpell();
extern SCM Script_typeRune();
extern SCM Script_typePowerCrystal();
extern SCM Script_typeCorpse();
extern SCM Script_typeDisease();
extern SCM Script_typeSymptom();

/* Crossfire Spells */
extern SCM Script_spellBullet();
extern SCM Script_spellSmallFireball();
extern SCM Script_spellMediumFireball();
extern SCM Script_spellLargeFireball();
extern SCM Script_spellBurningHands();
extern SCM Script_spellSmallLightning();
extern SCM Script_spellLargeLightning();
extern SCM Script_spellMagicMissile();
extern SCM Script_spellCreateBomb();
extern SCM Script_spellSummonGolem();
extern SCM Script_spellSummonFireElemental();
extern SCM Script_spellSummonEarthElemental();
extern SCM Script_spellSummonWaterElemental();
extern SCM Script_spellSummonAirElemental();
extern SCM Script_spellDimensionDoor();
extern SCM Script_spellCreateEarthWall();
extern SCM Script_spellParalyze();
extern SCM Script_spellIcestorm();
extern SCM Script_spellMagicMapping();
extern SCM Script_spellTurnUndead();
extern SCM Script_spellFear();
extern SCM Script_spellPoisonCloud();
extern SCM Script_spellWOW();
extern SCM Script_spellDestruction();
extern SCM Script_spellPerceiveSelf();
extern SCM Script_spellWOR();
extern SCM Script_spellInvisibility();
extern SCM Script_spellInvisibleToUndead();
extern SCM Script_spellProbe();
extern SCM Script_spellLargeBullet();
extern SCM Script_spellImprovedInvisibility();
extern SCM Script_spellHolyWord();
extern SCM Script_spellMinorHealing();
extern SCM Script_spellMediumHealing();
extern SCM Script_spellMajorHealing();
extern SCM Script_spellHeal();
extern SCM Script_spellCreateFood();
extern SCM Script_spellEarthToDust();
extern SCM Script_spellArmour();
extern SCM Script_spellStrength();
extern SCM Script_spellDexterity();
extern SCM Script_spellConstitution();
extern SCM Script_spellCharisma();
extern SCM Script_spellFireWall();
extern SCM Script_spellFrostWall();
extern SCM Script_spellProtectionCold();
extern SCM Script_spellProtectionElectricity();
extern SCM Script_spellProtectionFire();
extern SCM Script_spellProtectionPoison();
extern SCM Script_spellProtectionSlow();
extern SCM Script_spellProtectionParalyze();
extern SCM Script_spellProtectionDrain();
extern SCM Script_spellProtectionMagic();
extern SCM Script_spellProtectionAttack();
extern SCM Script_spellLevitate();
extern SCM Script_spellSmallSpeedball();
extern SCM Script_spellLargeSpeedball();
extern SCM Script_spellHellfire();
extern SCM Script_spellFirebreath();
extern SCM Script_spellLargeIcestorm();
extern SCM Script_spellCharging();
extern SCM Script_spellPolymorph();
extern SCM Script_spellCancellation();
extern SCM Script_spellConfusion();
extern SCM Script_spellMassConfusion();
extern SCM Script_spellSummonPetMonster();
extern SCM Script_spellSlow();
extern SCM Script_spellRegenerateSpellpoints();
extern SCM Script_spellCurePoison();
extern SCM Script_spellProtectionConfusion();
extern SCM Script_spellProtectionCancellation();
extern SCM Script_spellProtectionDepletion();
extern SCM Script_spellAlchemy();
extern SCM Script_spellRemoveCurse();
extern SCM Script_spellRemoveDamnation();
extern SCM Script_spellIdentify();
extern SCM Script_spellDetectMagic();
extern SCM Script_spellDetectMonster();
extern SCM Script_spellDetectEvil();
extern SCM Script_spellDetectCurse();
extern SCM Script_spellHeroism();
extern SCM Script_spellAggravation();
extern SCM Script_spellFirebolt();
extern SCM Script_spellFrostbolt();
extern SCM Script_spellShockwave();
extern SCM Script_spellColorSpray();
extern SCM Script_spellHaste();
extern SCM Script_spellFaceOfDeath();
extern SCM Script_spellBallLightning();
extern SCM Script_spellMeteorSwarm();
extern SCM Script_spellMeteor();
extern SCM Script_spellMysticFist();
extern SCM Script_spellRaiseDead();
extern SCM Script_spellResurrection();
extern SCM Script_spellReincarnation();
extern SCM Script_spellImmuneCold();
extern SCM Script_spellImmuneElectricity();
extern SCM Script_spellImmuneFire();
extern SCM Script_spellImmunePoison();
extern SCM Script_spellImmuneSlow();
extern SCM Script_spellImmuneParalyze();
extern SCM Script_spellImmuneDrain();
extern SCM Script_spellImmuneMagic();
extern SCM Script_spellImmuneAttack();
extern SCM Script_spellInvulnerability();
extern SCM Script_spellProtection();
extern SCM Script_spellRuneFire();
extern SCM Script_spellRuneFrost();
extern SCM Script_spellRuneShock();
extern SCM Script_spellRuneBlast();
extern SCM Script_spellRuneDeath();
extern SCM Script_spellRuneMark();
extern SCM Script_spellBuildDirector();
extern SCM Script_spellChaosPool();
extern SCM Script_spellBuildBulletWall();
extern SCM Script_spellBuildLightningWall();
extern SCM Script_spellBuildFireballWall();
extern SCM Script_spellRuneMagic();
extern SCM Script_spellRuneDrainSP();
extern SCM Script_spellRuneAntimagic();
extern SCM Script_spellRuneTransferrence();
extern SCM Script_spellTransfer();
extern SCM Script_spellMagicDrain();
extern SCM Script_spellCounterspell();
extern SCM Script_spellDispelRune();
extern SCM Script_spellCureConfusion();
extern SCM Script_spellRestoration();
extern SCM Script_spellSummonEvilMonster();
extern SCM Script_spellCounterwall();
extern SCM Script_spellCauseLightWounds();
extern SCM Script_spellCauseMediumWounds();
extern SCM Script_spellCauseHeavyWounds();
extern SCM Script_spellCharm();
extern SCM Script_spellBanishment();
extern SCM Script_spellCreateMissile();
extern SCM Script_spellShowInvisible();
extern SCM Script_spellXRay();
extern SCM Script_spellPacify();
extern SCM Script_spellSummonFog();
extern SCM Script_spellSteambolt();
extern SCM Script_spellCommandUndead();
extern SCM Script_spellHolyOrb();
extern SCM Script_spellSummonAvatar();
extern SCM Script_spellHolyPossession();
extern SCM Script_spellBless();
extern SCM Script_spellCurse();
extern SCM Script_spellRegeneration();
extern SCM Script_spellConsecrate();
extern SCM Script_spellSummonCultMonsters();
extern SCM Script_spellCauseCriticalWounds();
extern SCM Script_spellHolyWrath();
extern SCM Script_spellRetribution();
extern SCM Script_spellFingerDeath();
extern SCM Script_spellInsectPlague();
extern SCM Script_spellHolyServant();
extern SCM Script_spellWallOfThorns();
extern SCM Script_spellStaffToSnake();
extern SCM Script_spellLight();
extern SCM Script_spellDarkness();
extern SCM Script_spellNightfall();
extern SCM Script_spellDaylight();
extern SCM Script_spellSunSpear();
extern SCM Script_spellFaeryFire();
extern SCM Script_spellCureBlindness();
extern SCM Script_spellDarkVision();
extern SCM Script_spellBulletSwarm();
extern SCM Script_spellBulletStorm();
extern SCM Script_spellCauseManyWounds();
extern SCM Script_spellSmallSnowstorm();
extern SCM Script_spellMediumSnowstorm();
extern SCM Script_spellLargeSnowstorm();
extern SCM Script_spellCureDisease();
extern SCM Script_spellCauseEbola();
extern SCM Script_spellCauseFlu();
extern SCM Script_spellCausePlague();
extern SCM Script_spellCauseLeprosy();
extern SCM Script_spellCauseSmallPox();
extern SCM Script_spellCausePneumonicPlague();
extern SCM Script_spellCauseAnthrax();
extern SCM Script_spellCauseTyphoid();
extern SCM Script_spellManaBlast();
extern SCM Script_spellSmallManaball();
extern SCM Script_spellMediumManaball();
extern SCM Script_spellLargeManaball();
extern SCM Script_spellManabolt();
extern SCM Script_spellDancingSword();
extern SCM Script_spellAnimateWeapon();
extern SCM Script_spellCauseCold();
extern SCM Script_spellDivineShock();
extern SCM Script_spellWindStorm();
extern SCM Script_spellSanctuary();
extern SCM Script_spellPeace();
extern SCM Script_spellSpiderWeb();
extern SCM Script_spellConflict();
extern SCM Script_spellRage();
extern SCM Script_spellForkedLightning();
extern SCM Script_spellPoisonFog();
extern SCM Script_spellFlameAura();
extern SCM Script_spellVitriol();
extern SCM Script_spellVitriolSplash();
extern SCM Script_spellIronwoodSkin();
extern SCM Script_spellWrathfullEye();
