/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Mon Nov 13 22:09:19 2000
 */
#ifndef __CEXTRACT__
#ifdef __STDC__

extern void AddMeCmd ( char *buf, int len, NewSocket *ns );
extern void ApplyCmd ( char *buf, int len, player *pl );
extern void check_output_buffers ( object *pl, char *buf );
extern void clear_win_info ( object *op );
extern void cs_write_string ( NewSocket *ns, const char *buf, int len );
extern void doeric_server ( void );
extern void draw ( object *pl );
extern void draw_client_map ( object *pl );
extern void draw_map ( object *pl );
extern void esrv_del_item ( player *pl, int tag );
extern void esrv_draw_look ( object *pl );
extern object *esrv_get_ob_from_count ( object *pl, long count );
extern void esrv_map_scroll ( NewSocket *ns, int dx, int dy );
extern void esrv_move_object ( object *pl, long to, long tag, long nrof );
extern void esrv_new_player ( player *pl, uint32 weight );
extern void esrv_send_animation ( NewSocket *ns, short anim_num );
extern void esrv_send_face ( NewSocket *ns, short face_num, int nocache );
extern void esrv_send_inventory ( object *pl, object *op );
extern void esrv_send_item ( object *pl, object*op );
extern void esrv_update_item ( int flags, object *pl, object *op );
extern void esrv_update_stats ( player *pl );
extern void ExamineCmd ( char *buf, int len, player *pl );
extern void final_free_player ( player *pl );
extern void flush_output_element ( object *pl, Output_Buf *outputs );
extern void free_all_ericserver ( void );
extern void free_newsocket ( NewSocket *ns );
extern int GetInt_String ( unsigned char *data );
extern short GetShort_String ( unsigned char *data );
extern void HandleClient ( NewSocket *ns, player *pl );
extern void Handle_Oldsocket ( NewSocket *ns );
extern void InitConnection ( NewSocket *ns, uint32 from );
extern void init_ericserver ( void );
extern void LockItem ( uint8 *data, int len, player *pl );
extern void Log_Kill ( const char *Who, const char *What, int WhatType, const char *With, int WithType );
extern void LookAt ( char *buf, int len, player *pl );
extern void look_at ( object *op, int dx, int dy );
extern void magic_mapping_mark ( object *pl, char *map_mark, int strength );
extern void magic_mapping_mark_recursive ( object *pl, char *map_mark, int px, int py );
extern void MapRedrawCmd ( char *buff, int len, player *pl );
extern void MarkItem ( uint8 *data, int len, player *pl );
extern void metaserver_init ( void );
extern void metaserver_update ( void );
extern void MoveCmd ( char *buf, int len, player *pl );
extern void NewPlayerCmd ( uint8 *buf, int len, player *pl );
extern void new_draw_info ( int flags, int pri, object *pl, const char *buf );
extern void new_draw_info_format ( int flags, int pri, object *pl, char *format, ... );
extern void new_info_map ( int color, mapstruct *map, char *str );
extern void PlayerCmd ( char *buf, int len, player *pl );
extern void play_sound_map ( mapstruct *map, int x, int y, int sound_num );
extern void play_sound_player_only ( player *pl, int soundnum, int x, int y );
extern unsigned int query_flags ( object *op );
extern void rangetostring ( object *pl, char *obuf );
extern void read_client_images ( void );
extern void ReplyCmd ( char *buf, int len, player *pl );
extern void SendFaceCmd ( char *buff, int len, player *pl );
extern void send_query ( NewSocket *ns, uint8 flags, char *text );
extern void Send_With_Handling ( NewSocket *ns, SockList *msg );
extern void SetFaceMode ( char *buf, int len, NewSocket *ns );
extern void SetSound ( char *buf, int len, NewSocket *ns );
extern void set_title ( object *pl, char *buf );
extern void SockList_AddChar ( SockList *sl, char c );
extern void SockList_AddInt ( SockList *sl, uint32 data );
extern void SockList_AddShort ( SockList *sl, uint16 data );
extern void SockList_Init ( SockList *sl );
extern int SockList_ReadPacket ( int fd, SockList *sl, int len );
extern void VersionCmd ( char *buf, int len, NewSocket *ns );
extern void watchdog ( void );
extern void write_cs_stats ( void );
extern void write_socket_buffer ( NewSocket *ns );
extern void Write_String_To_Socket ( NewSocket *ns, char *buf, int len );
extern void Write_To_Socket ( NewSocket *ns, unsigned char *buf, int len );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
